Loading required package: ape
Loading required package: phytools
Loading required package: maps
Loading required package: phangorn
Loading required package: testit
Loading required package: tidyverse
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.5     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ purrr::map()    masks maps::map()
Loading required package: tools
Loading required package: reticulate
Loading required package: scales

Attaching package: ‘scales’

The following object is masked from ‘package:purrr’:

    discard

The following object is masked from ‘package:readr’:

    col_factor

Loading required package: rlist
Loading required package: BiocManager
Bioconductor version '3.12' is out-of-date; the current release version '3.13'
  is available with R version '4.1'; see https://bioconductor.org/install
Loading required package: naturalsort
[1] "reading trees..."
[1] "trees read; computing signal..."
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  CalledProcessError: Command '['/opt/software/Python/3.8.6-GCCcore-10.2.0/bin/python3', '/data/schwartzlab/alex/andromeda_tools/Rlib_4.0.3/Rboretum/Alignment_Splits.py', '/data/schwartzlab/eren/Chapter1/Concord_Analyses/IQOutput/RBoretumIN/Alignments/intron_concat.fasta', 'AnaPla;ApaVit;AptFor;BalReg;BucRhi;CarCri;ChaPel;ChaVoc;ChlMac;ColLiv;ColStr;CorBra;CucCan;EurHel;FalPer;FulGla;GalGal;GavSte;HalLeu;LepDis;MelUnd;MerNub;MesUni;OpiHoa;PelCri;PhaLep;PhoRub;PicPub;PteGut;StrCam;TauEry;TytAlb', '0', 'intron_concat.fasta']' died with <Signals.SIGKILL: 9>.

Detailed traceback:
  File "<string>", line 63, in rb_run_align_splits
  File "/opt/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
Calls: getAlignmentSignal ... <Anonymous> -> .f -> rb_run_align_splits -> py_call_impl
Execution halted
